FROM node:10-jessie

WORKDIR /src
ADD . .

ARG CI_JOB_AUTH

RUN apt-get update && \
    apt-get -y install git

RUN if [ ! -z "${CI_JOB_AUTH}" ] ; then git config --global url.http://${CI_JOB_AUTH}@gitlab.steventaylor.me/.insteadOf http://gitlab.steventaylor.me/ ; fi

RUN npm install && \
    apt-get -y remove git && \
    npm install

EXPOSE 5000

CMD ["node", "app.js"]